const fs = require('fs');
const path = require('path');

const componentsDir = path.join(process.cwd(), 'src/components');

function walkDir(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      if (['providers', 'SEO', 'analytics', 'tests'].includes(file)) continue;
      walkDir(filePath, fileList);
    } else {
      if (file.endsWith('.tsx') && !file.endsWith('.stories.tsx') && !file.endsWith('.test.tsx') && file !== 'index.tsx') {
        fileList.push(filePath);
      }
    }
  }
  return fileList;
}

const componentFiles = walkDir(componentsDir);

let generatedCount = 0;

for (const fullPath of componentFiles) {
  const parsedPath = path.parse(fullPath);
  const storyPath = path.join(parsedPath.dir, `${parsedPath.name}.stories.tsx`);

  if (!fs.existsSync(storyPath)) {
    const componentName = parsedPath.name;
    const content = fs.readFileSync(fullPath, 'utf8');
    
    // Check if there is an export that matches the filename
    const exportPattern1 = new RegExp(`export\\s+(default\\s+)?(function|const|let|var|class)\\s+${componentName}\\b`);
    const exportPattern2 = new RegExp(`export\\s+\\{\\s*${componentName}\\s*\\}`);
    const exportPattern3 = new RegExp(`export\\s+default\\s+${componentName}\\b`);

    if (!exportPattern1.test(content) && !exportPattern2.test(content) && !exportPattern3.test(content)) {
      console.log(`Skipping ${componentName} - no matching export found`);
      continue;
    }

    const storyContent = `import type { Meta, StoryObj } from "@storybook/react/dist/index";
import { ${componentName} } from "./${componentName}";

/**
 * 🍍 JOLANANAS - ${componentName}
 * ==============================
 * Auto-generated Storybook file.
 */
const meta: Meta<typeof ${componentName}> = {
  title: "JOLANANAS/AutoGenerated/${componentName}",
  component: ${componentName},
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ${componentName}>;

export const Default: Story = {
  args: {},
};
`;
    
    fs.writeFileSync(storyPath, storyContent);
    console.log(`Generated story for ${componentName}`);
    generatedCount++;
  }
}

console.log(`\nFinished! Generated ${generatedCount} new stories.`);
